<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Library</OutputType>
        <RootNamespace>ValheimPerformanceOptimizations</RootNamespace>
        <AssemblyName>ValheimPerformanceOptimizations</AssemblyName>
        <TargetFramework>netstandard2.1</TargetFramework>
        <LangVersion>latest</LangVersion>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <Import Project="..\Environment.props" />

    <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
        <DefineConstants>DEBUG;TRACE;ENABLE_PROFILER;_DEBUG</DefineConstants>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)' == 'Release'">
        <DefineConstants>TRACE</DefineConstants>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="BepInEx.Analyzers" Version="1.*" PrivateAssets="all"/>
        <PackageReference Include="BepInEx.Core" Version="5.*" />
        <PackageReference Include="BepInEx.PluginInfoProps" Version="1.*"/>
        <PackageReference Include="UnityEngine.Modules" Version="6000.0.61" >
            <IncludeAssets>all</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="BepInEx.AssemblyPublicizer.MSBuild" Version="0.4.3" PrivateAssets="all" />
    </ItemGroup>

    <ItemGroup>
        <Reference Include="0Harmony, Culture=neutral, PublicKeyToken=null">
            <HintPath>$(VALHEIM_INSTALL)\BepInEx\core\0Harmony.dll</HintPath>
        </Reference>
        <Reference Include="assembly_guiutils" Publicize="true">
            <HintPath>$(VALHEIM_INSTALL)\valheim_Data\Managed\assembly_guiutils.dll</HintPath>
        </Reference>
        <Reference Include="assembly_utils" Publicize="true">
            <HintPath>$(VALHEIM_INSTALL)\valheim_Data\Managed\assembly_utils.dll</HintPath>
        </Reference>
        <Reference Include="assembly_valheim" Publicize="true">
            <HintPath>$(VALHEIM_INSTALL)\valheim_Data\Managed\assembly_valheim.dll</HintPath>
        </Reference>
        <Reference Include="Jotunn, Culture=neutral, PublicKeyToken=null">
            <HintPath Condition="Exists('$(VALHEIM_INSTALL)\BepInEx\plugins\Jotunn.dll')">$(VALHEIM_INSTALL)\BepInEx\plugins\Jotunn.dll</HintPath>
            <HintPath Condition="Exists('$(R2MODMAN_INSTALL)\BepInEx\plugins\ValheimModding-Jotunn\Jotunn.dll')">$(R2MODMAN_INSTALL)\BepInEx\plugins\ValheimModding-Jotunn\Jotunn.dll</HintPath>
        </Reference>
        <Reference Include="Unity.Mathematics">
            <HintPath>$(VALHEIM_INSTALL)\valheim_Data\Managed\Unity.Mathematics.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.UI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null">
            <HintPath>$(VALHEIM_INSTALL)\unstripped_corlib\UnityEngine.UI.dll</HintPath>
        </Reference>
        <Reference Include="VPOBurst_Managed">
            <HintPath>BurstOutput\VPOBurst_Managed.dll</HintPath>
            <Private>true</Private>
        </Reference>
        <Reference Include="Unity.Burst">
            <HintPath>BurstOutput\Unity.Burst.dll</HintPath>
            <Private>true</Private>
        </Reference>
    </ItemGroup>
    <ItemGroup>
        <EmbeddedResource Include="AssetBundles\smoke_instanced_shader" />
    </ItemGroup>
    <ItemGroup>
        <None Include="BurstOutput\VPOBurst_win_x86_64.dll" Condition="Exists('BurstOutput\VPOBurst_win_x86_64.dll')">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <Link>VPOBurst_win_x86_64.dll</Link>
        </None>
        <None Include="BurstOutput\Unity.Burst.Unsafe.dll" Condition="Exists('BurstOutput\Unity.Burst.Unsafe.dll')">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <Link>Unity.Burst.Unsafe.dll</Link>
        </None>
    </ItemGroup>
    <PropertyGroup Condition="'$(Configuration)' == 'Release'">
        <PostBuildEvent>
            powershell Compress-Archive -Path '$(ProjectDir)Package\*' -DestinationPath '$(SolutionDir)PublishOutput\$(MSBuildProjectName).zip' -Force
            xcopy "$(TargetDir)" "$(VALHEIM_INSTALL)\BepInEx\plugins\$(MSBuildProjectName)\" /q /s /y /i
        </PostBuildEvent>
    </PropertyGroup>
</Project>